import 'enums/warm_up_exercise.dart';
import 'models/exercises.dart';
import 'models/sport.dart';

List<Sport> sports = [
  Sport(
    id: 0,
    name: 'Football',
    imageLocalPath: 'images/sport_icons/am_football.png',
    exercise: Exercises(
      exerciseLength: 20,
      exerciseWorkTimes: [
        20,
        20,
        20,
        0,
        0,
        0,
        20,
        20,
        20,
        30,
        60,
        0,
        0,
        0,
        20,
        20,
        30,
        30,
        20,
        20,
      ],
      exerciseHints: [
        '2x 20sek + beidseitig,Punkt fixieren für Gleichgewicht,fester Stand,Knie berühren sich,Hüfte leicht nach vorne schieben',
        '2x 20sek + beidseitig,Fersen am Boden,hinteres Bein durchgestreckt,Gewicht nach vorne schieben,gerader Rücken',
        'beidseitig + 2x 20sek,Gesäß Richtung Boden',
        '20 Wdh.,vorsichtig ausführen,Knie auf Bauchnabelhöhe',
        '20 Wdh.,Knie auf Bauchnabelhöhe',
        '20 Wdh. + beidseitig,vorsichtig ausführen,nicht ruckartig,Füße auf Bauchnabel-/Gesichtshöhe',
        '2x 20sek + beidseitig,Standbein gestreckt,Gerader Rücken,Knie Richtung Brust',
        '2x 20sek + beidseitig,vorsichtig ausführen',
        '2x 20sek + beidseitig,Zehenspitzen berühren,Bein durchstrecken',
        '2x 30sek + beidseitig,Oberkörper dreht sich auf,Knie vorsichtig drücken,Blick nach hinten,Stützarm unter der Schulter',
        '60sek,gerader Rücken,Boden angucken',
        '20-30Wdh.,Körperspannung,Gesicht nah an Boden',
        '15 Wdh.,Richtung Boden gucken',
        '10 Wdh.',
        '2x 20sek + beidseitig,nicht ruckartig,Arme Kreisen',
        '20sek.,vorsichtig ausführen',
        '30sek,Handgelenke entspannt kreisen',
        '30sek,Finger strecken,Finger zur Handfläche',
        '2x 20sek + beidseitig,vorsichtig ausführen,Fingerspitzen Richtung Gesicht drücken,Arm gestreckt',
        '2x 20sek + beidseitig,Arm gegen Wand drücken,Oberkörper dreht auf',
      ],
      exerciseRepetition: [
        '2x 20sek',
        '2x 20sek',
        '2x 20sek',
        '20 Wdh.',
        '20 Wdh.',
        '20 Wdh.',
        '2x 20sek',
        '2x 20sek',
        '2x 20sek',
        '2x 30sek',
        '60sek',
        '20-30Wdh.',
        '15 Wdh.',
        '10 Wdh.',
        '2x 20sek',
        '20sek.',
        '30sek',
        '30sek',
        '2x 20sek',
        '2x 20sek',
      ],
      exerciseGifs: [
        'images/gif_exercises/am_football/1Sport26.jpeg',
        'images/gif_exercises/am_football/2Sport19.jpeg',
        'images/gif_exercises/am_football/3Sport03.jpeg',
        'images/gif_exercises/am_football/4Sport32.gif',
        'images/gif_exercises/am_football/5aSport31.gif',
        'images/gif_exercises/am_football/5bSport34.gif',
        'images/gif_exercises/am_football/6aSport09.jpeg',
        'images/gif_exercises/am_football/6bSport40.gif',
        'images/gif_exercises/am_football/7Sport10.jpeg',
        'images/gif_exercises/am_football/8Sport15.jpeg',
        'images/gif_exercises/am_football/9Sport17.jpeg',
        'images/gif_exercises/am_football/10Sport39.gif',
        'images/gif_exercises/am_football/11Sport48.gif',
        'images/gif_exercises/am_football/12Sport42.gif',
        'images/gif_exercises/am_football/13Sport36.gif',
        'images/gif_exercises/am_football/14Sport44.gif',
        'images/gif_exercises/am_football/15Sport04.gif',
        'images/gif_exercises/am_football/16Sport35.gif',
        'images/gif_exercises/am_football/17Sport27.jpeg',
        'images/gif_exercises/am_football/18Sport25.jpeg',
      ],
      exerciseNames: [
        'Oberschenkel',
        'Wade',
        'Leiste ',
        'Adduktoren und Abduktoren',
        'Anknien',
        'Adduktoren',
        'Adduktoren',
        'Fußgelenke kreisen',
        'Beine',
        'Abduktoren',
        'Unterarmstütz',
        'Liegestütze',
        'Rückentraining',
        'Kommando',
        'Mobilität',
        'Ellbogen kreisen',
        'Handgelenke kreisen',
        'Handflächen',
        'Hand',
        'Brustmuskulatur',
      ],
      warmUpModes: [
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withoutTime,
        WarmUpExercise.withoutTime,
        WarmUpExercise.withoutTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withoutTime,
        WarmUpExercise.withoutTime,
        WarmUpExercise.withoutTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
      ],
    ),
  ),
  Sport(
    id: 1,
    name: 'Hockey',
    imageLocalPath: 'images/sport_icons/hockey.png',
    exercise: Exercises(
      exerciseLength: 10,
      exerciseWorkTimes: [20, 20, 0, 20, 0, 60, 0, 20, 0, 20],
      exerciseGifs: [
        'images/gif_exercises/hockey/1Sport26.jpeg',
        'images/gif_exercises/hockey/2Sport19.jpeg',
        'images/gif_exercises/hockey/3Sport02.gif',
        'images/gif_exercises/hockey/4Sport10.jpeg',
        'images/gif_exercises/hockey/5Sport42.gif',
        'images/gif_exercises/hockey/6Sport17.jpeg',
        'images/gif_exercises/hockey/7Sport06.gif',
        'images/gif_exercises/hockey/8Sport40.gif',
        'images/gif_exercises/hockey/9Sport48.gif',
        'images/gif_exercises/hockey/10Sport25.jpeg',
      ],
      exerciseHints: [
        '2x 20sek + beidseitig,Punkt fixieren für Gleichgewicht,fester Stand,Knie berühren sich,Hüfte leicht nach vorne schieben',
        '2x 20sek + beidseitig,Fersen am Boden,hinteres Bein durchgestreckt,Gewicht nach vorne schieben,gerader Rücken',
        '10 Wdh,Knie nicht über Fußspitzen,gerader Rücken,Gesäß nach hinten strecken',
        '2x 20sek + beidseitig,Zehenspitzen berühren,Bein durchstrecken',
        '10 Wdh.',
        '60sek,gerader Rücken,Boden angucken',
        '20 Wdh.,Körperspannung,Gesicht nah an Boden,Richtung Boden gucken',
        '2x 20sek + beidseitig,vorsichtig ausführen',
        '15 Wdh.,Richtung Boden gucken',
        '2x 20sek + beidseitig,Arm gegen Wand drücken,Oberkörper dreht auf',
      ],
      exerciseNames: [
        'Oberschenkel',
        'Wade',
        'Kniebeuge',
        'Beine',
        'Kommando',
        'Unterarmstütz',
        'Liegestück und unterer Rücken',
        'Fußgelenke kreisen',
        'Rückentraining',
        'Brustmuskulatur',
      ],
      exerciseRepetition: [
        '2x 20sek',
        '2x 20sek',
        '10 Wdh',
        '2x 20sek',
        '10 Wdh.',
        '60sek',
        '20 Wdh.',
        '2x 20sek',
        '15 Wdh.',
        '2x 20sek',
      ],
      warmUpModes: [
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withoutTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withoutTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withoutTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withoutTime,
        WarmUpExercise.withTime
      ],
    ),
  ),
  Sport(
    id: 2,
    name: 'Volleyball',
    imageLocalPath: 'images/sport_icons/volleyball.png',
    exercise: Exercises(
      exerciseLength: 13,
      exerciseGifs: [
        'images/gif_exercises/volleyball/1Sport26.jpeg',
        'images/gif_exercises/volleyball/2Sport19.jpeg',
        'images/gif_exercises/volleyball/3Sport01.gif',
        'images/gif_exercises/volleyball/4Sport31.gif',
        'images/gif_exercises/volleyball/5Sport49.gif',
        'images/gif_exercises/volleyball/6Sport28.gif',
        'images/gif_exercises/volleyball/7Sport13.jpeg',
        'images/gif_exercises/volleyball/8Sport04.gif',
        'images/gif_exercises/volleyball/9Sport27.jpeg',
        'images/gif_exercises/volleyball/10Sport35.gif',
        'images/gif_exercises/volleyball/11Sport06.gif',
        'images/gif_exercises/volleyball/12Sport17.jpeg',
        'images/gif_exercises/volleyball/13Sport39.gif',
      ],
      exerciseHints: [
        '2x 20sek + beidseitig,Punkt fixieren für Gleichgewicht,fester Stand,Knie berühren sich,Hüfte leicht nach vorne schieben',
        '2x 20sek + beidseitig,Fersen am Boden,hinteres Bein durchgestreckt,Gewicht nach vorne schieben,gerader Rücken',
        'beidseitig + 2x 20sek,Knöchel entspannt kreisen,gerader Rücken',
        '20 Wdh.,Knie auf Bauchnabelhöhe',
        '50 Wdh.',
        '20sek,vorsichtig ausführen,kleine Kreise machen',
        '2x 20sek + beidseitig,Arm Richtung Brust ziehen,nicht ruckartig',
        '30sek,Handgelenke entspannt kreisen',
        '2x 20sek + beidseitig,vorsichtig ausführen,Fingerspitzen Richtung Gesicht drücken,Arm gestreckt',
        '30sek,Finger strecken,Finger zur Handfläche',
        '20 Wdh.,Körperspannung,Gesicht nah an Boden,Richtung Boden gucken',
        '60sek,gerader Rücken,Boden angucken',
        '20-30Wdh.,Körperspannung,Gesicht nah an Boden',
      ],
      exerciseWorkTimes: [
        20,
        20,
        20,
        0,
        0,
        20,
        20,
        30,
        20,
        30,
        0,
        60,
        0,
      ],
      exerciseNames: [
        'Oberschenkel',
        'Wade',
        'Knöchel kreisen',
        'Anknien',
        'Seilchenspringen',
        'Knie kreisen',
        'Trizeps und Schultergelenk',
        'Handgelenke kreisen',
        'Hand',
        'Handflächen',
        'Liegestück und unterer Rücken',
        'Unterarmstütz',
        'Liegestütze',
      ],
      exerciseRepetition: [
        '2x 20sek',
        '2x 20sek',
        '2x 20sek',
        '20 Wdh.',
        '50 Wdh.',
        '20sek',
        '2x 20sek',
        '30sek',
        '2x 20sek',
        '30sek',
        '20 Wdh.',
        '60sek',
        '20-30Wdh.',
      ],
      warmUpModes: [
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withoutTime,
        WarmUpExercise.withoutTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withoutTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withoutTime
      ],
    ),
  ),
  Sport(
    id: 3,
    name: 'Basketball',
    imageLocalPath: 'images/sport_icons/basketball.png',
    exercise: Exercises(
      exerciseLength: 13,
      exerciseWorkTimes: [20, 20, 0, 0, 20, 20, 0, 30, 30, 20, 60, 0, 20],
      exerciseGifs: [
        'images/gif_exercises/basketball/1Sport26.jpeg',
        'images/gif_exercises/basketball/2Sport19.jpeg',
        'images/gif_exercises/basketball/3Sport31.gif',
        'images/gif_exercises/basketball/4Sport02.gif',
        'images/gif_exercises/basketball/5Sport28.gif',
        'images/gif_exercises/basketball/6Sport40.gif',
        'images/gif_exercises/basketball/7Sport49.gif',
        'images/gif_exercises/basketball/8Sport04.gif',
        'images/gif_exercises/basketball/9Sport35.gif',
        'images/gif_exercises/basketball/10Sport27.jpeg',
        'images/gif_exercises/basketball/11Sport17.jpeg',
        'images/gif_exercises/basketball/12Sport39.gif',
        'images/gif_exercises/basketball/13Sport24.jpeg',
      ],
      exerciseHints: [
        '2x 20sek + beidseitig,Punkt fixieren für Gleichgewicht,fester Stand,Knie berühren sich,Hüfte leicht nach vorne schieben',
        '2x 20sek + beidseitig,Fersen am Boden,hinteres Bein durchgestreckt,Gewicht nach vorne schieben,gerader Rücken',
        '20 Wdh.,Knie auf Bauchnabelhöhe',
        '10 Wdh.,Knie nicht über Fußspitzen,gerader Rücken,Gesäß nach hinten strecken',
        '20sek.,vorsichtig ausführen,kleine Kreise machen',
        '2x 20sek + beidseitig,vorsichtig ausführen',
        '50 Wdh.',
        '30sek.,Handgelenke entspannt kreisen',
        '30sek.,Finger strecken,Finger zur Handfläche',
        '2x 20sek + beidseitig,vorsichtig ausführen,Fingerspitzen Richtung Gesicht drücken,Arm gestreckt',
        '60sek.,gerader Rücken,Boden angucken',
        '20-30Wdh.,Körperspannung,Gesicht nah an Boden',
        '2x 20sek + beidseitig,Arm gegen Wand drücken,Oberkörper dreht auf',
      ],
      exerciseNames: [
        'Oberschenkel',
        'Wade',
        'Anknien',
        'Kniebeuge',
        'Knie kreisen',
        'Kommando mit Burpee',
        'Seilchenspringen',
        'Handgelenke kreisen',
        'Handflächen',
        'Hand',
        'Unterarmstütz',
        'Liegestütze',
        'Brustmuskulatur',
      ],
      exerciseRepetition: [
        '2x 20sek',
        '2x 20sek',
        '20 Wdh.',
        '10 Wdh.',
        '20sek.',
        '2x 20sek',
        '50 Wdh.',
        '30sek.',
        '30sek.',
        '2x 20sek',
        '60sek',
        '20-30Wdh.',
        '2x 20sek',
      ],
      warmUpModes: [
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withoutTime,
        WarmUpExercise.withoutTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withoutTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withoutTime,
        WarmUpExercise.withTime,
      ],
    ),
  ),
  Sport(
    id: 4,
    name: 'Tennis',
    imageLocalPath: 'images/sport_icons/tennis.png',
    exercise: Exercises(
      exerciseLength: 12,
      exerciseWorkTimes: [
        20,
        20,
        20,
        20,
        0,
        20,
        0,
        0,
        20,
        20,
        30,
        20,
      ],
      exerciseGifs: [
        'images/gif_exercises/tennis/1Sport26.jpeg', //gif
        'images/gif_exercises/tennis/2Sport19.jpeg', //gif
        'images/gif_exercises/tennis/3Sport40.gif', //gif
        'images/gif_exercises/tennis/4Sport10.jpeg', //gif
        'images/gif_exercises/tennis/5Sport43.gif', //gif
        'images/gif_exercises/tennis/6Sport01.gif', //gif
        'images/gif_exercises/tennis/7Sport39.gif', //gif
        'images/gif_exercises/tennis/8Sport42.gif', //gif
        'images/gif_exercises/tennis/9Sport36.gif', //gif
        'images/gif_exercises/tennis/10Sport44.gif', //gif
        'images/gif_exercises/tennis/11Sport04.gif', //gif
        'images/gif_exercises/tennis/12Sport25.jpeg', //gif
      ],
      exerciseHints: [
        '2x 20sek + beidseitig,Punkt fixieren für Gleichgewicht,fester Stand,Knie berühren sich,Hüfte leicht nach vorne schieben',
        '2x 20sek + beidseitig,Fersen am Boden,hinteres Bein durchgestreckt,Gewicht nach vorne schieben,gerader Rücken',
        '2x 20sek + beidseitig,vorsichtig ausführen',
        '2x 20sek + beidseitig,Zehenspitzen berühren,Bein durchstrecken',
        '20 Wdh. + beidseitig,Ellbogen bleiben auf Boden',
        'beidseitig + 2x 20sek,Knöchel entspannt kreisen,gerader Rücken',
        '20-30Wdh.,Körperspannung,Gesicht nah an Boden',
        '10 Wdh.',
        '2x 20sek + beidseitig,nicht ruckartig,Arme Kreisen',
        '20sek.,vorsichtig ausführen',
        '30sek.,Handgelenke entspannt kreisen',
        '2x 20sek + beidseitig,Arm gegen Wand drücken,Oberkörper dreht auf',
      ],
      exerciseRepetition: [
        '2x 20sek',
        '2x 20sek',
        '2x 20sek',
        '2x 20sek',
        '20 Wdh.',
        '2x 20sek',
        '20-30Wdh.',
        '10 Wdh.',
        '2x 20sek',
        '20sek.',
        '30sek.',
        '2x 20sek.',
      ],
      warmUpModes: [
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withoutTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withoutTime,
        WarmUpExercise.withoutTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
      ],
      exerciseNames: [
        'Oberschenkel',
        'Wade',
        'Fußgelenke kreisen',
        'Beine',
        'Unterarmstütz mit Hüfte',
        'Knöchel kreisen',
        'Liegestütze',
        'Kommando',
        'Mobilität',
        'Ellbogen kreisen',
        'Handgelenke kreisen',
        'Brustmuskulatur',
      ],
    ),
  ),
  Sport(
    id: 5,
    name: 'Ballspiele',
    imageLocalPath: 'images/sport_icons/ball_spiele.png',
    exercise: Exercises(
      exerciseLength: 20,
      exerciseGifs: [
        'images/gif_exercises/ball_games/1Sport26.jpeg', //gif
        'images/gif_exercises/ball_games/2Sport19.jpeg', //gif
        'images/gif_exercises/ball_games/3Sport03.jpeg', //gif
        'images/gif_exercises/ball_games/4Sport32.gif', //gif
        'images/gif_exercises/ball_games/5aSport31.gif', //gif
        'images/gif_exercises/ball_games/5bSport34.gif', //gif
        'images/gif_exercises/ball_games/6aSport09.jpeg', //gif
        'images/gif_exercises/ball_games/6bSport40.gif', //gif
        'images/gif_exercises/ball_games/7Sport10.jpeg', //gif
        'images/gif_exercises/ball_games/8Sport15.jpeg', //gif
        'images/gif_exercises/ball_games/9Sport17.jpeg', //gif
        'images/gif_exercises/ball_games/10Sport39.gif', //gif
        'images/gif_exercises/ball_games/11Sport48.gif', //gif
        'images/gif_exercises/ball_games/12Sport42.gif', //gif
        'images/gif_exercises/ball_games/13Sport36.gif', //gif
        'images/gif_exercises/ball_games/14Sport44.gif', //gif
        'images/gif_exercises/ball_games/15Sport04.gif', //gif
        'images/gif_exercises/ball_games/16Sport35.gif', //gif
        'images/gif_exercises/ball_games/17Sport27.jpeg', //gif
        'images/gif_exercises/ball_games/18Sport25.jpeg', //gif
      ],
      exerciseWorkTimes: [
        20,
        20,
        20,
        0,
        0,
        0,
        20,
        20,
        20,
        30,
        60,
        0,
        0,
        0,
        20,
        20,
        30,
        30,
        20,
        20,
      ],
      exerciseHints: [
        '2x 20sek + beidseitig,Punkt fixieren für Gleichgewicht,fester Stand,Knie berühren sich,Hüfte leicht nach vorne schieben',
        '2x 20sek + beidseitig,Fersen am Boden,hinteres Bein durchgestreckt,Gewicht nach vorne schieben,gerader Rücken',
        'beidseitig + 2x 20sek,Gesäß Richtung Boden',
        '20 Wdh.,vorsichtig ausführen,Knie auf Bauchnabelhöhe',
        '20 Wdh.,Knie auf Bauchnabelhöhe',
        '20 Wdh. + beidseitig,vorsichtig ausführen,nicht ruckartig,Füße auf Bauchnabel-/Gesichtshöhe',
        '2x 20sek + beidseitig,Standbein gestreckt,Gerader Rücken,Knie Richtung Brust',
        '2x 20sek + beidseitig,vorsichtig ausführen',
        '2x 20sek + beidseitig,Zehenspitzen berühren,Bein durchstrecken',
        '2x 30sek + beidseitig,Oberkörper dreht sich auf,Knie vorsichtig drücken,Blick nach hinten,Stützarm unter der Schulter',
        '60sek.,gerader Rücken,Boden angucken',
        '20-30Wdh.,Körperspannung,Gesicht nah an Boden',
        '15 Wdh.,Richtung Boden gucken',
        '10 Wdh.',
        '2x 20sek + beidseitig,nicht ruckartig,Arme Kreisen',
        '20sek.,vorsichtig ausführen',
        '30sek.,Handgelenke entspannt kreisen',
        '30sek.,Finger strecken,Finger zur Handfläche',
        '2x 20sek + beidseitig,vorsichtig ausführen,Fingerspitzen Richtung Gesicht drücken,Arm gestreckt',
        '2x 20sek + beidseitig,Arm gegen Wand drücken,Oberkörper dreht auf',
      ],
      exerciseRepetition: [
        '2x 20sek',
        '2x 20sek',
        '2x 20sek',
        '20 Wdh.',
        '20 Wdh.',
        '20 Wdh.',
        '2x 20sek',
        '2x 20sek',
        '2x 20sek',
        '2x 30sek.',
        '60sek.',
        '20-30Wdh.',
        '15 Wdh.',
        '10 Wdh.',
        '2x 20sek',
        '20sek.',
        '30sek.',
        '30sek.',
        '2x 20sek',
        '2x 20sek',
      ],
      warmUpModes: [
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withoutTime,
        WarmUpExercise.withoutTime,
        WarmUpExercise.withoutTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withoutTime,
        WarmUpExercise.withoutTime,
        WarmUpExercise.withoutTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
      ],
      exerciseNames: [
        'Oberschenkel',
        'Wade',
        'Leiste',
        'Adduktoren und Abduktoren',
        'Anknien',
        'Adduktoren',
        'Adduktoren',
        'Fußgelenke kreisen',
        'Beine',
        'Abduktoren',
        'Unterarmstütz',
        'Liegestütze',
        'Rückentraining',
        'Kommando',
        'Mobilität',
        'Ellbogen kreisen',
        'Handgelenke kreisen',
        'Handflächen',
        'Hand',
        'Brustmuskulatur',
      ],
    ),
  ),
  Sport(
    id: 6,
    name: 'Badminton',
    imageLocalPath: 'images/sport_icons/badminton.png',
    exercise: Exercises(
      exerciseLength: 12,
      exerciseGifs: [
        'images/gif_exercises/badminton/1Sport26.jpeg', //gif
        'images/gif_exercises/badminton/2Sport19.jpeg', //gif
        'images/gif_exercises/badminton/3Sport40.gif', //gif
        'images/gif_exercises/badminton/4Sport10.jpeg', //gif
        'images/gif_exercises/badminton/5Sport43.gif', //gif
        'images/gif_exercises/badminton/6Sport01.gif', //gif
        'images/gif_exercises/badminton/7Sport39.gif', //gif
        'images/gif_exercises/badminton/8Sport42.gif', //gif
        'images/gif_exercises/badminton/9Sport36.gif', //gif
        'images/gif_exercises/badminton/10Sport44.gif', //gif
        'images/gif_exercises/badminton/11Sport04.gif', //gif
        'images/gif_exercises/badminton/12Sport25.jpeg', //gif
      ],
      exerciseWorkTimes: [
        20,
        20,
        20,
        20,
        0,
        20,
        0,
        0,
        20,
        20,
        30,
        20,
      ],
      warmUpModes: [
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withoutTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withoutTime,
        WarmUpExercise.withoutTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
      ],
      exerciseHints: [
        '2x 20sek + beidseitig,Punkt fixieren für Gleichgewicht,fester Stand,Knie berühren sich,Hüfte leicht nach vorne schieben',
        '2x 20sek + beidseitig,Fersen am Boden,hinteres Bein durchgestreckt,Gewicht nach vorne schieben,gerader Rücken',
        '2x 20sek + beidseitig,vorsichtig ausführen',
        '2x 20sek + beidseitig,Zehenspitzen berühren,Bein durchstrecken',
        '20 Wdh. + beidseitig,Ellbogen bleiben auf Boden',
        'beidseitig + 2x 20sek,Knöchel entspannt kreisen,gerader Rücken',
        '20-30Wdh.,Körperspannung,Gesicht nah an Boden',
        '10 Wdh.',
        '2x 20sek + beidseitig,nicht ruckartig,Arme Kreisen',
        '20sek.,vorsichtig ausführen',
        '30sek.,Handgelenke entspannt kreisen',
        '2x 20sek + beidseitig,Arm gegen Wand drücken,Oberkörper dreht auf',
      ],
      exerciseRepetition: [
        '2x 20sek',
        '2x 20sek',
        '2x 20sek',
        '2x 20sek',
        '20 Wdh.',
        '2x 20sek',
        '20-30Wdh.',
        '10 Wdh.',
        '2x 20sek',
        '20sek.',
        '30sek.',
        '2x 20sek.',
      ],
      exerciseNames: [
        'Oberschenkel',
        'Wade',
        'Fußgelenke kreisen',
        'Beine',
        'Unterarmstütz mit Hüfte',
        'Knöchel kreisen',
        'Liegestütze',
        'Kommando',
        'Mobilität',
        'Ellbogen kreisen',
        'Handgelenke kreisen',
        'Brustmuskulatur',
      ],
    ),
  ),
  Sport(
    id: 7,
    name: 'Fußball',
    imageLocalPath: 'images/sport_icons/football.png',
    exercise: Exercises(
      exerciseLength: 14,
      exerciseGifs: [
        'images/gif_exercises/football/1Sport26.jpeg', //gif
        'images/gif_exercises/football/2Sport19.jpeg', //gif
        'images/gif_exercises/football/3Sport03.jpeg', //gif
        'images/gif_exercises/football/4Sport09.jpeg', //gif
        'images/gif_exercises/football/5Sport32.gif', //gif
        'images/gif_exercises/football/6Sport40.gif', //gif
        'images/gif_exercises/football/7Sport30.gif', //gif
        'images/gif_exercises/football/8Sport34.gif', //gif
        'images/gif_exercises/football/9Sport31.gif', //gif
        'images/gif_exercises/football/10Sport10.jpeg', //gif
        'images/gif_exercises/football/11Sport43.gif', //gif
        'images/gif_exercises/football/12Sport17.jpeg', //gif
        'images/gif_exercises/football/13Sport06.gif', //gif
        'images/gif_exercises/football/14Sport39.gif', //gif
      ],
      exerciseHints: [
        '2x 20sek + beidseitig,Punkt fixieren für Gleichgewicht,fester Stand,Knie berühren sich,Hüfte leicht nach vorne schieben',
        '2x 20sek + beidseitig,Fersen am Boden,hinteres Bein durchgestreckt,Gewicht nach vorne schieben,gerader Rücken',
        'beidseitig + 2x 20sek.,Gesäß Richtung Boden',
        '2x 20sek + beidseitig,Standbein gestreckt,Gerader Rücken,Knie Richtung Brust',
        '20 Wdh.,vorsichtig ausführen,Knie auf Bauchnabelhöhe',
        '2x 20sek + beidseitig,vorsichtig ausführen',
        '20 Wdh.,Ferse Richtung Gesäß',
        '20 Wdh. + beidseitig,vorsichtig ausführen,nicht ruckartig,Füße auf Bauchnabel-/Gesichtshöhe',
        '20 Wdh.,Knie auf Bauchnabelhöhe',
        '2x 20sek + beidseitig,Zehenspitzen berühren,Bein durchstrecken',
        '20 Wdh. + beidseitig,Ellbogen bleiben auf Boden',
        '60sek.,gerader Rücken,Boden angucken',
        '20 Wdh.,Körperspannung,Gesicht nah an Boden,Richtung Boden gucken',
        '20-30Wdh.,Körperspannung,Gesicht nah an Boden',
      ],
      exerciseRepetition: [
        '2x 20sek',
        '2x 20sek',
        '2x 20sek',
        '2x 20sek',
        '20 Wdh.',
        '2x 20sek',
        '20 Wdh.',
        '20 Wdh.',
        '20 Wdh.',
        '2x 20sek',
        '20 Wdh.',
        '60sek.',
        '20 Wdh.',
        '20-30Wdh.',
      ],
      exerciseWorkTimes: [
        20,
        20,
        20,
        20,
        0,
        20,
        0,
        0,
        0,
        20,
        0,
        60,
        0,
        0,
      ],
      warmUpModes: [
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withoutTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withoutTime,
        WarmUpExercise.withoutTime,
        WarmUpExercise.withoutTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withoutTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withoutTime,
        WarmUpExercise.withoutTime,
      ],
      exerciseNames: [
        'Oberschenkel',
        'Wade',
        'Leiste',
        'Adduktoren',
        'Adduktoren und Abduktoren',
        'Fußgelenke kreisen',
        'Anfersen',
        'Adduktoren',
        'Anknien',
        'Beine',
        'Unterarmstütz mit Hüfte',
        'Unterarmstütz',
        'Liegestück und unterer Rücken',
        'Liegestütze',
      ],
    ),
  ),
  Sport(
    id: 8,
    name: 'Tischtennis',
    imageLocalPath: 'images/sport_icons/ping-pong.png',
    exercise: Exercises(
      exerciseLength: 8,
      exerciseGifs: [
        'images/gif_exercises/ping_pong/1Sport19.jpeg', //gif
        'images/gif_exercises/ping_pong/2Sport40.gif', //gif
        'images/gif_exercises/ping_pong/3Sport29.gif', //gif
        'images/gif_exercises/ping_pong/4Sport10.jpeg', //gif
        'images/gif_exercises/ping_pong/5Sport06.gif', //gif
        'images/gif_exercises/ping_pong/6Sport01.gif', //gif
        'images/gif_exercises/ping_pong/7Sport17.jpeg', //gif
        'images/gif_exercises/ping_pong/8Sport24.jpeg', //gif
      ],
      exerciseHints: [
        '2x 20sek + beidseitig,Fersen am Boden,hinteres Bein durchgestreckt,Gewicht nach vorne schieben,gerader Rücken',
        '2x 20sek + beidseitig,vorsichtig ausführen',
        '2x 20sek + beidseitig,nicht ruckartig,Fußgelenke entspannt kreisen',
        '2x 20sek + beidseitig,Zehenspitzen berühren,Bein durchstrecken',
        '20 Wdh.,Körperspannung,Gesicht nah an Boden,Richtung Boden gucken',
        'beidseitig + 2x 20sek,Knöchel entspannt kreisen,gerader Rücken',
        '60sek.,gerader Rücken,Boden angucken',
        '2x 20sek + beidseitig,Arm gegen Wand drücken,Oberkörper dreht auf',
      ],
      exerciseRepetition: [
        '2x 20sek.',
        '2x 20sek.',
        '2x 20sek.',
        '2x 20sek.',
        '20 Wdh.',
        '2x 20sek.',
        '60sek.',
        '2x 20sek.',
      ],
      exerciseWorkTimes: [
        20,
        20,
        20,
        20,
        0,
        20,
        60,
        20,
      ],
      warmUpModes: [
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withoutTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
      ],
      exerciseNames: [
        'Wade',
        'Fußgelenke kreisen',
        'Fußgelenk kreisen',
        'Beine',
        'Liegestück und unterer Rücken',
        'Knöchel kreisen',
        'Unterarmstütz',
        'Brustmuskulatur',
      ],
    ),
  ),
  Sport(
    id: 9,
    name: 'Fitness',
    imageLocalPath: 'images/sport_icons/fitness1.png',
    exercise: Exercises(
      exerciseLength: 11,
      exerciseGifs: [
        'images/gif_exercises/fitness/1Sport19.jpeg', //gif
        'images/gif_exercises/fitness/2Sport47.gif', //gif
        'images/gif_exercises/fitness/3Sport43.gif', //gif
        'images/gif_exercises/fitness/4Sport49.gif', //gif
        'images/gif_exercises/fitness/5Sport42.gif', //gif
        'images/gif_exercises/fitness/6Sport39.gif', //gif
        'images/gif_exercises/fitness/7Sport05.gif', //gif
        'images/gif_exercises/fitness/8Sport46.gif', //gif
        'images/gif_exercises/fitness/9Sport10.jpeg', //gif
        'images/gif_exercises/fitness/10Sport06.gif', //gif
        'images/gif_exercises/fitness/11Sport25.jpeg', //gif
      ],
      exerciseHints: [
        '2x 20sek + beidseitig,Fersen am Boden,hinteres Bein durchgestreckt,Gewicht nach vorne schieben,gerader Rücken',
        '20 Wdh.',
        '20 Wdh. + beidseitig,Ellbogen bleiben auf Boden',
        '50 Wdh.',
        '10 Wdh.',
        '20-30Wdh.,Körperspannung,Gesicht nah an Boden',
        '10 Wdh.,Körperspannung,Gesicht nah an Boden,hoch springen',
        '10 Wdh. + beidseitig',
        '2x 20sek + beidseitig,Zehenspitzen berühren,Bein durchstrecken',
        '20 Wdh.,Körperspannung,Gesicht nah an Boden,Richtung Boden gucken',
        '2x 20sek + beidseitig,Arm gegen Wand drücken,Oberkörper dreht auf',
      ],
      exerciseRepetition: [
        '2x 20sek',
        '20 Wdh.',
        '20 Wdh.',
        '50 Wdh.',
        '10 Wdh.',
        '20-30Wdh.',
        '10 Wdh.',
        '10 Wdh.',
        '2x 20sek',
        '20 Wdh.',
        '2x 20sek',
      ],
      exerciseWorkTimes: [
        20,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        20,
        0,
        20,
      ],
      warmUpModes: [
        WarmUpExercise.withTime,
        WarmUpExercise.withoutTime,
        WarmUpExercise.withoutTime,
        WarmUpExercise.withoutTime,
        WarmUpExercise.withoutTime,
        WarmUpExercise.withoutTime,
        WarmUpExercise.withoutTime,
        WarmUpExercise.withoutTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withoutTime,
        WarmUpExercise.withTime,
      ],
      exerciseNames: [
        'Wade',
        'Bergsteigen',
        'Unterarmstütz mit Hüfte',
        'Seilchenspringen',
        'Kommando',
        'Liegestütze',
        'Burpees',
        'Kniebeuge Umsprung',
        'Beine',
        'Liegestück und unterer Rücken',
        'Brustmuskulatur',
      ],
    ),
  ),
  Sport(
    id: 10,
    name: 'Joggen',
    imageLocalPath: 'images/sport_icons/running.png',
    exercise: Exercises(
      exerciseLength: 7,
      exerciseGifs: [
        'images/gif_exercises/running/1Sport26.jpeg', //gif
        'images/gif_exercises/running/2Sport19.jpeg', //gif
        'images/gif_exercises/running/3Sport32.gif', //gif
        'images/gif_exercises/running/4Sport02.gif', //gif
        'images/gif_exercises/running/5Sport30.gif', //gif
        'images/gif_exercises/running/6Sport31.gif', //gif
        'images/gif_exercises/running/7Sport09.jpeg', //gif
      ],
      exerciseHints: [
        '2x 20sek + beidseitig,Punkt fixieren für Gleichgewicht,fester Stand,Knie berühren sich,Hüfte leicht nach vorne schieben',
        '2x 20sek + beidseitig,Fersen am Boden,hinteres Bein durchgestreckt,Gewicht nach vorne schieben,gerader Rücken',
        '20 Wdh.,vorsichtig ausführen,Knie auf Bauchnabelhöhe',
        '10 Wdh.,Knie nicht über Fußspitzen,gerader Rücken,Gesäß nach hinten strecken',
        '20 Wdh.,Ferse Richtung Gesäß',
        '20 Wdh.,Knie auf Bauchnabelhöhe',
        '2x 20sek + beidseitig,Standbein gestreckt,Gerader Rücken,Knie Richtung Brust',
      ],
      exerciseWorkTimes: [
        20,
        20,
        0,
        0,
        0,
        0,
        20,
      ],
      exerciseRepetition: [
        '2x 20sek',
        '2x 20sek',
        '20 Wdh',
        '10 Wdh',
        '20 Wdh',
        '20 Wdh.',
        '2x 20sek.',
      ],
      exerciseNames: [
        'Oberschenkel',
        'Wade',
        'Adduktoren und Abduktoren',
        'Kniebeuge',
        'Anfersen',
        'Anknien',
        'Adduktoren',
      ],
      warmUpModes: [
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withoutTime,
        WarmUpExercise.withoutTime,
        WarmUpExercise.withoutTime,
        WarmUpExercise.withoutTime,
        WarmUpExercise.withTime,
      ],
    ),
  ),
  Sport(
    id: 11,
    name: 'Schwimmen',
    imageLocalPath: 'images/sport_icons/swimming.png',
    exercise: Exercises(
      exerciseLength: 5,
      exerciseGifs: [
        'images/gif_exercises/swimming/1Sport19.jpeg', //gif
        'images/gif_exercises/swimming/2Sport36.gif', //gif
        'images/gif_exercises/swimming/3Sport04.gif', //gif
        'images/gif_exercises/swimming/4Sport35.gif', //gif
        'images/gif_exercises/swimming/5Sport25.jpeg', //gif
      ],
      exerciseNames: [
        'Wade',
        'Mobilität',
        'Handgelenke kreisen',
        'Handflächen',
        'Brustmuskulatur',
      ],
      exerciseHints: [
        '2x 20sek + beidseitig,Fersen am Boden,hinteres Bein durchgestreckt,Gewicht nach vorne schieben,gerader Rücken',
        '2x 20sek + beidseitig,nicht ruckartig,Arme Kreisen',
        '30sek.,Handgelenke entspannt kreisen',
        '30sek.,Finger strecken,Finger zur Handfläche',
        '2x 20sek + beidseitig,Arm gegen Wand drücken,Oberkörper dreht auf',
      ],
      exerciseWorkTimes: [
        20,
        20,
        30,
        30,
        20,
      ],
      exerciseRepetition: [
        '2x 20sek',
        '2x 20sek',
        '30sek.',
        '30sek.',
        '2x 20sek',
      ],
      warmUpModes: [
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
      ],
    ),
  ),
  Sport(
    id: 12,
    name: 'Turnen',
    imageLocalPath: 'images/sport_icons/gymnastics.png',
    exercise: Exercises(
      exerciseLength: 25,
      exerciseGifs: [
        'images/gif_exercises/gymnastics/1Sport26.jpeg', //gif
        'images/gif_exercises/gymnastics/2aSport19.jpeg', //gif
        'images/gif_exercises/gymnastics/2bSport03.jpeg', //gif
        'images/gif_exercises/gymnastics/3Sport08.gif', //gif
        'images/gif_exercises/gymnastics/4Sport09.jpeg', //gif
        'images/gif_exercises/gymnastics/5Sport29.gif', //gif
        'images/gif_exercises/gymnastics/6Sport28.gif', //gif
        'images/gif_exercises/gymnastics/7aSport40.gif', //gif
        'images/gif_exercises/gymnastics/7bSport11.jpeg', //gif
        'images/gif_exercises/gymnastics/7cSport12.jpeg', //gif
        'images/gif_exercises/gymnastics/7dSport20.jpeg', //gif
        'images/gif_exercises/gymnastics/7eSport15.jpeg', //gif
        'images/gif_exercises/gymnastics/8Sport35.gif', //gif
        'images/gif_exercises/gymnastics/9Sport36.gif', //gif
        'images/gif_exercises/gymnastics/10Sport14.jpeg', //gif
        'images/gif_exercises/gymnastics/11Sport21.jpeg', //gif
        'images/gif_exercises/gymnastics/12Sport13.jpeg', //gif
        'images/gif_exercises/gymnastics/13Sport04.gif', //gif
        'images/gif_exercises/gymnastics/14Sport22.jpeg', //gif
        'images/gif_exercises/gymnastics/15Sport23.jpeg', //gif
        'images/gif_exercises/gymnastics/16Sport07.gif', //gif
        'images/gif_exercises/gymnastics/17Sport25.jpeg', //gif
        'images/gif_exercises/gymnastics/18Sport27.jpeg', //gif
        'images/gif_exercises/gymnastics/19Sport39.gif', //gif
        'images/gif_exercises/gymnastics/20Sport48.gif', //gif
      ],
      exerciseNames: [
        'Oberschenkel',
        'Wade',
        'Leiste',
        'Mobilisierung Hüftbeuger',
        'Adduktoren',
        'Fußgelenk kreisen',
        'Knie kreisen',
        'Fußgelenke kreisen',
        'Adduktoren',
        'Abduktoren',
        'Mobilität',
        'Abduktoren',
        'Handflächen',
        'Mobilität',
        'Trizeps und Schultergelenk',
        'Mobilität',
        'Trizeps und Schultergelenk',
        'Handgelenke kreisen',
        'Nackenmuskulatur',
        'Nackenmuskulatur',
        'Nackenmuskulatur',
        'Brustmuskulatur',
        'Hand',
        'Liegestütze',
        'Rückentraining',
      ],
      exerciseHints: [
        '2x 20sek + beidseitig,Punkt fixieren für Gleichgewicht,fester Stand,Knie berühren sich,Hüfte leicht nach vorne schieben',
        '2x 20sek + beidseitig,Fersen am Boden,hinteres Bein durchgestreckt,Gewicht nach vorne schieben,gerader Rücken',
        'beidseitig + 2x 20sek.,Gesäß Richtung Boden',
        '30sek.,schulterbreiter Stand,große Kreise,schnell ausführen',
        '2x 20sek + beidseitig,Standbein gestreckt,Gerader Rücken,Knie Richtung Brust',
        '2x 20sek + beidseitig,nicht ruckartig,Fußgelenke entspannt kreisen',
        '20sek.,vorsichtig ausführen,kleine Kreise machen',
        '2x 20sek + beidseitig,vorsichtig ausführen',
        '30sek.,Fersen nah an den Körper,Gerader Rücken,Knie Richtung Boden ziehen,Erweiterung: Mit den Ellbogen Druck auf Knie ausüben',
        '30sek.,Stirn Richtung Füße,Füße weg vom Körper,Hände umfassen Fußspitzen',
        '20sek.,Oberkörper nach vorne unten führen,Beine sind gestreckt,Zehen oder Boden berühren',
        '2x 30sek + beidseitig,Oberkörper dreht sich auf,Knie vorsichtig drücken,Blick nach hinten,Stützarm unter der Schulter',
        '30sek.,Finger strecken,Finger zur Handfläche',
        '2x 20sek. + beidseitig,nicht ruckartig,Arme Kreisen',
        '2x 20sek + beidseitig,Handfläche zwischen Schulterblätter,Gegenarm zieht am Ellbogen',
        '20sek.,nicht ruckartig,Arme hinterm Rücken fassen,Arme strecken',
        '2x 20sek + beidseitig,Arm Richtung Brust ziehen,nicht ruckartig',
        '30sek.,Handgelenke entspannt kreisen',
        '2x 30sek + beidseitig,Gerader - schulterbreiter Stand,vorsichtig ausführen,Kopf drückt gegen Hand,Hand drückt leicht gegen Kopf',
        '2x 30sek + beidseitig,Gerader - schulterbreiter Stand,vorsichtig ausführen,Kopf drückt gegen Hand,Hand drückt leicht gegen Kopf',
        '20sek.,Kopf langsam in jede Richtung,vorsichtig ausführen,Schultern entspannt,nicht kreisen',
        '2x 20sek + beidseitig,Arm gegen Wand drücken,Oberkörper dreht auf',
        '2x 20sek + beidseitig,vorsichtig ausführen,Fingerspitzen Richtung Gesicht drücken,Arm gestreckt',
        '20-30Wdh.,Körperspannung,Gesicht nah an Boden',
        '15 Wdh.,Richtung Boden gucken',
      ],
      exerciseRepetition: [
        '2x 20sek',
        '2x 20sek',
        '2x 20sek',
        '30sek',
        '2x 20sek',
        '2x 20sek',
        '20sek.',
        '2x 20sek',
        '30sek.',
        '30sek.',
        '20sek.',
        '2x 30sek',
        '30sek',
        '2x 20sek.',
        '2x 20sek.',
        '20sek.',
        '2x 20sek',
        '30sek.',
        '2x 30sek',
        '2x 30sek',
        '20Sek.',
        '2x 20sek',
        '2x 20sek',
        '20-30Wdh.',
        '15 Wdh.',
      ],
      exerciseWorkTimes: [
        20,
        20,
        20,
        30,
        20,
        20,
        20,
        20,
        30,
        30,
        20,
        30,
        30,
        20,
        20,
        20,
        20,
        30,
        30,
        30,
        20,
        20,
        20,
        0,
        0,
      ],
      warmUpModes: [
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withoutTime,
        WarmUpExercise.withoutTime,
      ],
    ),
  ),
  Sport(
    id: 13,
    name: 'Parcours',
    imageLocalPath: 'images/sport_icons/parcours.png',
    exercise: Exercises(
      exerciseLength: 25,
      exerciseGifs: [
        'images/gif_exercises/gymnastics/1Sport26.jpeg', //gif
        'images/gif_exercises/gymnastics/2aSport19.jpeg', //gif
        'images/gif_exercises/gymnastics/2bSport03.jpeg', //gif
        'images/gif_exercises/gymnastics/3Sport08.gif', //gif
        'images/gif_exercises/gymnastics/4Sport09.jpeg', //gif
        'images/gif_exercises/gymnastics/5Sport29.gif', //gif
        'images/gif_exercises/gymnastics/6Sport28.gif', //gif
        'images/gif_exercises/gymnastics/7aSport40.gif', //gif
        'images/gif_exercises/gymnastics/7bSport11.jpeg', //gif
        'images/gif_exercises/gymnastics/7cSport12.jpeg', //gif
        'images/gif_exercises/gymnastics/7dSport20.jpeg', //gif
        'images/gif_exercises/gymnastics/7eSport15.jpeg', //gif
        'images/gif_exercises/gymnastics/8Sport35.gif', //gif
        'images/gif_exercises/gymnastics/9Sport36.gif', //gif
        'images/gif_exercises/gymnastics/10Sport14.jpeg', //gif
        'images/gif_exercises/gymnastics/11Sport21.jpeg', //gif
        'images/gif_exercises/gymnastics/12Sport13.jpeg', //gif
        'images/gif_exercises/gymnastics/13Sport04.gif', //gif
        'images/gif_exercises/gymnastics/14Sport22.jpeg', //gif
        'images/gif_exercises/gymnastics/15Sport23.jpeg', //gif
        'images/gif_exercises/gymnastics/16Sport07.gif', //gif
        'images/gif_exercises/gymnastics/17Sport25.jpeg', //gif
        'images/gif_exercises/gymnastics/18Sport27.jpeg', //gif
        'images/gif_exercises/gymnastics/19Sport39.gif', //gif
        'images/gif_exercises/gymnastics/20Sport48.gif', //gif
      ],
      exerciseNames: [
        'Oberschenkel',
        'Wade',
        'Leiste',
        'Mobilisierung Hüftbeuger',
        'Adduktoren',
        'Fußgelenk kreisen',
        'Knie kreisen',
        'Fußgelenke kreisen',
        'Adduktoren',
        'Abduktoren',
        'Mobilität',
        'Abduktoren',
        'Handflächen',
        'Mobilität',
        'Trizeps und Schultergelenk',
        'Mobilität',
        'Trizeps und Schultergelenk',
        'Handgelenke kreisen',
        'Nackenmuskulatur',
        'Nackenmuskulatur',
        'Nackenmuskulatur',
        'Brustmuskulatur',
        'Hand',
        'Liegestütze',
        'Rückentraining',
      ],
      exerciseHints: [
        '2x 20sek + beidseitig,Punkt fixieren für Gleichgewicht,fester Stand,Knie berühren sich,Hüfte leicht nach vorne schieben',
        '2x 20sek + beidseitig,Fersen am Boden,hinteres Bein durchgestreckt,Gewicht nach vorne schieben,gerader Rücken',
        'beidseitig + 2x 20sek.,Gesäß Richtung Boden',
        '30sek.,schulterbreiter Stand,große Kreise,schnell ausführen',
        '2x 20sek + beidseitig,Standbein gestreckt,Gerader Rücken,Knie Richtung Brust',
        '2x 20sek + beidseitig,nicht ruckartig,Fußgelenke entspannt kreisen',
        '20sek.,vorsichtig ausführen,kleine Kreise machen',
        '2x 20sek + beidseitig,vorsichtig ausführen',
        '30sek.,Fersen nah an den Körper,Gerader Rücken,Knie Richtung Boden ziehen,Erweiterung: Mit den Ellbogen Druck auf Knie ausüben',
        '30sek.,Stirn Richtung Füße,Füße weg vom Körper,Hände umfassen Fußspitzen',
        '20sek.,Oberkörper nach vorne unten führen,Beine sind gestreckt,Zehen oder Boden berühren',
        '2x 30sek + beidseitig,Oberkörper dreht sich auf,Knie vorsichtig drücken,Blick nach hinten,Stützarm unter der Schulter',
        '30sek.,Finger strecken,Finger zur Handfläche',
        '2x 20sek. + beidseitig,nicht ruckartig,Arme Kreisen',
        '2x 20sek + beidseitig,Handfläche zwischen Schulterblätter,Gegenarm zieht am Ellbogen',
        '20sek.,nicht ruckartig,Arme hinterm Rücken fassen,Arme strecken',
        '2x 20sek + beidseitig,Arm Richtung Brust ziehen,nicht ruckartig',
        '30sek.,Handgelenke entspannt kreisen',
        '2x 30sek + beidseitig,Gerader - schulterbreiter Stand,vorsichtig ausführen,Kopf drückt gegen Hand,Hand drückt leicht gegen Kopf',
        '2x 30sek + beidseitig,Gerader - schulterbreiter Stand,vorsichtig ausführen,Kopf drückt gegen Hand,Hand drückt leicht gegen Kopf',
        '20sek.,Kopf langsam in jede Richtung,vorsichtig ausführen,Schultern entspannt,nicht kreisen',
        '2x 20sek + beidseitig,Arm gegen Wand drücken,Oberkörper dreht auf',
        '2x 20sek + beidseitig,vorsichtig ausführen,Fingerspitzen Richtung Gesicht drücken,Arm gestreckt',
        '20-30Wdh.,Körperspannung,Gesicht nah an Boden',
        '15 Wdh.,Richtung Boden gucken',
      ],
      exerciseRepetition: [
        '2x 20sek',
        '2x 20sek',
        '2x 20sek',
        '30sek',
        '2x 20sek',
        '2x 20sek',
        '20sek.',
        '2x 20sek',
        '30sek.',
        '30sek.',
        '20sek.',
        '2x 30sek',
        '30sek',
        '2x 20sek.',
        '2x 20sek.',
        '20sek.',
        '2x 20sek',
        '30sek.',
        '2x 30sek',
        '2x 30sek',
        '20Sek.',
        '2x 20sek',
        '2x 20sek',
        '20-30Wdh.',
        '15 Wdh.',
      ],
      exerciseWorkTimes: [
        20,
        20,
        20,
        30,
        20,
        20,
        20,
        20,
        30,
        30,
        20,
        30,
        30,
        20,
        20,
        20,
        20,
        30,
        30,
        30,
        20,
        20,
        20,
        0,
        0,
      ],
      warmUpModes: [
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withoutTime,
        WarmUpExercise.withoutTime,
      ],
    ),
  ),
  Sport(
    id: 14,
    name: 'Bouldern-Klettern',
    imageLocalPath: 'images/sport_icons/climbing.png',
    exercise: Exercises(
      exerciseLength: 25,
      exerciseGifs: [
        'images/gif_exercises/gymnastics/1Sport26.jpeg', //gif
        'images/gif_exercises/gymnastics/2aSport19.jpeg', //gif
        'images/gif_exercises/gymnastics/2bSport03.jpeg', //gif
        'images/gif_exercises/gymnastics/3Sport08.gif', //gif
        'images/gif_exercises/gymnastics/4Sport09.jpeg', //gif
        'images/gif_exercises/gymnastics/5Sport29.gif', //gif
        'images/gif_exercises/gymnastics/6Sport28.gif', //gif
        'images/gif_exercises/gymnastics/7aSport40.gif', //gif
        'images/gif_exercises/gymnastics/7bSport11.jpeg', //gif
        'images/gif_exercises/gymnastics/7cSport12.jpeg', //gif
        'images/gif_exercises/gymnastics/7dSport20.jpeg', //gif
        'images/gif_exercises/gymnastics/7eSport15.jpeg', //gif
        'images/gif_exercises/gymnastics/8Sport35.gif', //gif
        'images/gif_exercises/gymnastics/9Sport36.gif', //gif
        'images/gif_exercises/gymnastics/10Sport14.jpeg', //gif
        'images/gif_exercises/gymnastics/11Sport21.jpeg', //gif
        'images/gif_exercises/gymnastics/12Sport13.jpeg', //gif
        'images/gif_exercises/gymnastics/13Sport04.gif', //gif
        'images/gif_exercises/gymnastics/14Sport22.jpeg', //gif
        'images/gif_exercises/gymnastics/15Sport23.jpeg', //gif
        'images/gif_exercises/gymnastics/16Sport07.gif', //gif
        'images/gif_exercises/gymnastics/17Sport25.jpeg', //gif
        'images/gif_exercises/gymnastics/18Sport27.jpeg', //gif
        'images/gif_exercises/gymnastics/19Sport39.gif', //gif
        'images/gif_exercises/gymnastics/20Sport48.gif', //gif
      ],
      exerciseNames: [
        'Oberschenkel',
        'Wade',
        'Leiste',
        'Mobilisierung Hüftbeuger',
        'Adduktoren',
        'Fußgelenk kreisen',
        'Knie kreisen',
        'Fußgelenke kreisen',
        'Adduktoren',
        'Abduktoren',
        'Mobilität',
        'Abduktoren',
        'Handflächen',
        'Mobilität',
        'Trizeps und Schultergelenk',
        'Mobilität',
        'Trizeps und Schultergelenk',
        'Handgelenke kreisen',
        'Nackenmuskulatur',
        'Nackenmuskulatur',
        'Nackenmuskulatur',
        'Brustmuskulatur',
        'Hand',
        'Liegestütze',
        'Rückentraining',
      ],
      exerciseHints: [
        '2x 20sek + beidseitig,Punkt fixieren für Gleichgewicht,fester Stand,Knie berühren sich,Hüfte leicht nach vorne schieben',
        '2x 20sek + beidseitig,Fersen am Boden,hinteres Bein durchgestreckt,Gewicht nach vorne schieben,gerader Rücken',
        'beidseitig + 2x 20sek.,Gesäß Richtung Boden',
        '30sek.,schulterbreiter Stand,große Kreise,schnell ausführen',
        '2x 20sek + beidseitig,Standbein gestreckt,Gerader Rücken,Knie Richtung Brust',
        '2x 20sek + beidseitig,nicht ruckartig,Fußgelenke entspannt kreisen',
        '20sek.,vorsichtig ausführen,kleine Kreise machen',
        '2x 20sek + beidseitig,vorsichtig ausführen',
        '30sek.,Fersen nah an den Körper,Gerader Rücken,Knie Richtung Boden ziehen,Erweiterung: Mit den Ellbogen Druck auf Knie ausüben',
        '30sek.,Stirn Richtung Füße,Füße weg vom Körper,Hände umfassen Fußspitzen',
        '20sek.,Oberkörper nach vorne unten führen,Beine sind gestreckt,Zehen oder Boden berühren',
        '2x 30sek + beidseitig,Oberkörper dreht sich auf,Knie vorsichtig drücken,Blick nach hinten,Stützarm unter der Schulter',
        '30sek.,Finger strecken,Finger zur Handfläche',
        '2x 20sek. + beidseitig,nicht ruckartig,Arme Kreisen',
        '2x 20sek + beidseitig,Handfläche zwischen Schulterblätter,Gegenarm zieht am Ellbogen',
        '20sek.,nicht ruckartig,Arme hinterm Rücken fassen,Arme strecken',
        '2x 20sek + beidseitig,Arm Richtung Brust ziehen,nicht ruckartig',
        '30sek.,Handgelenke entspannt kreisen',
        '2x 30sek + beidseitig,Gerader - schulterbreiter Stand,vorsichtig ausführen,Kopf drückt gegen Hand,Hand drückt leicht gegen Kopf',
        '2x 30sek + beidseitig,Gerader - schulterbreiter Stand,vorsichtig ausführen,Kopf drückt gegen Hand,Hand drückt leicht gegen Kopf',
        '20sek.,Kopf langsam in jede Richtung,vorsichtig ausführen,Schultern entspannt,nicht kreisen',
        '2x 20sek + beidseitig,Arm gegen Wand drücken,Oberkörper dreht auf',
        '2x 20sek + beidseitig,vorsichtig ausführen,Fingerspitzen Richtung Gesicht drücken,Arm gestreckt',
        '20-30Wdh.,Körperspannung,Gesicht nah an Boden',
        '15 Wdh.,Richtung Boden gucken',
      ],
      exerciseRepetition: [
        '2x 20sek',
        '2x 20sek',
        '2x 20sek',
        '30sek',
        '2x 20sek',
        '2x 20sek',
        '20sek.',
        '2x 20sek',
        '30sek.',
        '30sek.',
        '20sek.',
        '2x 30sek',
        '30sek',
        '2x 20sek.',
        '2x 20sek.',
        '20sek.',
        '2x 20sek',
        '30sek.',
        '2x 30sek',
        '2x 30sek',
        '20Sek.',
        '2x 20sek',
        '2x 20sek',
        '20-30Wdh.',
        '15 Wdh.',
      ],
      exerciseWorkTimes: [
        20,
        20,
        20,
        30,
        20,
        20,
        20,
        20,
        30,
        30,
        20,
        30,
        30,
        20,
        20,
        20,
        20,
        30,
        30,
        30,
        20,
        20,
        20,
        0,
        0,
      ],
      warmUpModes: [
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withoutTime,
        WarmUpExercise.withoutTime,
      ],
    ),
  ),
  Sport(
    id: 15,
    name: 'Leichtathletik',
    imageLocalPath: 'images/sport_icons/athletics.png',
    exercise: Exercises(
      exerciseLength: 19,
      exerciseGifs: [
        'images/gif_exercises/athletics/1Sport26.jpeg', //gif
        'images/gif_exercises/athletics/2Sport19.jpeg', //gif
        'images/gif_exercises/athletics/3Sport03.jpeg', //gif
        'images/gif_exercises/athletics/4Sport31.gif', //gif
        'images/gif_exercises/athletics/5Sport09.jpeg', //gif
        'images/gif_exercises/athletics/6Sport32.gif', //gif
        'images/gif_exercises/athletics/7Sport02.gif', //gif
        'images/gif_exercises/athletics/8Sport33.gif', //gif
        'images/gif_exercises/athletics/9Sport01.gif', //gif
        'images/gif_exercises/athletics/10Sport10.jpeg', //gif
        'images/gif_exercises/athletics/11Sport15.jpeg', //gif
        'images/gif_exercises/athletics/12Sport06.gif', //gif
        'images/gif_exercises/athletics/13Sport17.jpeg', //gif
        'images/gif_exercises/athletics/14Sport39.gif', //gif
        'images/gif_exercises/athletics/15Sport34.gif', //gif
        'images/gif_exercises/athletics/16Sport28.gif', //gif
        'images/gif_exercises/athletics/17Sport08.gif', //gif
        'images/gif_exercises/athletics/18Sport18.jpeg', //gif
        'images/gif_exercises/athletics/19Sport24.jpeg', //gif
      ],
      exerciseNames: [
        'Oberschenkel',
        'Wade',
        'Leiste',
        'Anknien',
        'Adduktoren',
        'Adduktoren und Abduktoren',
        'Kniebeuge',
        'Adduktoren',
        'Knöchel kreisen',
        'Beine',
        'Abduktoren',
        'Liegestück und unterer Rücken',
        'Unterarmstütz',
        'Liegestütze',
        'Adduktoren',
        'Knie kreisen',
        'Mobilisierung Hüftbeuger',
        'Wirbelsäule',
        'Brustmuskulatur',
      ],
      exerciseHints: [
        '2x 20sek + beidseitig,Punkt fixieren für Gleichgewicht,fester Stand,Knie berühren sich,Hüfte leicht nach vorne schieben',
        '2x 20sek + beidseitig,Fersen am Boden,hinteres Bein durchgestreckt,Gewicht nach vorne schieben,gerader Rücken',
        'beidseitig + 2x 20sek,Gesäß Richtung Boden',
        '20 Wdh.,Knie auf Bauchnabelhöhe',
        '2x 20sek + beidseitig,Standbein gestreckt,Gerader Rücken,Knie Richtung Brust',
        '20 Wdh.,vorsichtig ausführen,Knie auf Bauchnabelhöhe',
        '10 Wdh.,Knie nicht über Fußspitzen,gerader Rücken,Gesäß nach hinten strecken',
        '20 Wdh. + beidseitig,vorsichtig ausführen,am Knöchel anfassen,Körper in eine Waagerechte bringen',
        'beidseitig + 2x 20sek.,Knöchel entspannt kreisen,gerader Rücken',
        '2x 20sek + beidseitig,Zehenspitzen berühren,Bein durchstrecken',
        '2x 30sek + beidseitig,Oberkörper dreht sich auf,Knie vorsichtig drücken,Blick nach hinten,Stützarm unter der Schulter',
        '20 Wdh.,Körperspannung,Gesicht nah an Boden,Richtung Boden gucken',
        '60sek.,gerader Rücken,Boden angucken',
        '20-30Wdh.,Körperspannung,Gesicht nah an Boden',
        '20 Wdh. + beidseitig,vorsichtig ausführen,nicht ruckartig,Füße auf Bauchnabel-/Gesichtshöhe',
        '20sek.,vorsichtig ausführen,kleine Kreise machen',
        '30sek.,schulterbreiter Stand,große Kreise,schnell ausführen',
        '6 Wdh. auf jeder Seite,nicht ruckartig ausführen',
        '2x 20sek + beidseitig,Arm gegen Wand drücken,Oberkörper dreht auf',
      ],
      exerciseRepetition: [
        '2x 20sek',
        '2x 20sek',
        '2x 20sek',
        '20 Wdh.',
        '2x 20sek',
        '20 Wdh.',
        '10 Wdh.',
        '20 Wdh.',
        '2x 20sek.',
        '2x 20sek.',
        '2x 30sek',
        '20 Wdh.',
        '60sek.',
        '20-30Wdh.',
        '20 Wdh.',
        '20sek.',
        '30sek.',
        '6 Wdh.',
        '2x 20sek',
      ],
      exerciseWorkTimes: [
        20,
        20,
        20,
        0,
        20,
        0,
        0,
        0,
        20,
        20,
        30,
        0,
        60,
        0,
        0,
        20,
        30,
        0,
        20,
      ],
      warmUpModes: [
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withoutTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withoutTime,
        WarmUpExercise.withoutTime,
        WarmUpExercise.withoutTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withoutTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withoutTime,
        WarmUpExercise.withoutTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withTime,
        WarmUpExercise.withoutTime,
        WarmUpExercise.withTime,
      ],
    ),
  ),
];
